# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_uploadedimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
    ]
